In [3]:
!pip list

Package          Version  
---------------- ---------
backcall         0.1.0    
certifi          2019.6.16
colorama         0.4.1    
cx-Oracle        7.2.1    
decorator        4.4.0    
ipykernel        5.1.1    
ipython          7.7.0    
ipython-genutils 0.2.0    
jedi             0.14.1   
jupyter-client   5.3.1    
jupyter-core     4.5.0    
numpy            1.17.0   
pandas           0.25.0   
parso            0.5.1    
pickleshare      0.7.5    
pip              19.1.1   
prompt-toolkit   2.0.9    
Pygments         2.4.2    
python-dateutil  2.8.0    
pytz             2019.2   
pyzmq            18.0.2   
setuptools       41.0.1   
six              1.12.0   
tornado          6.0.3    
traitlets        4.3.2    
wcwidth          0.1.7    
wheel            0.33.4   
wincertstore     0.2      


In [4]:
!conda list

# packages in environment at C:\Users\student\Anaconda3\envs\multi:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                    pypi_0    pypi
certifi                   2019.6.16                py36_1  
colorama                  0.4.1                    pypi_0    pypi
cx-oracle                 7.2.1                    pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
ipykernel                 5.1.1                    pypi_0    pypi
ipython                   7.7.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.14.1                   pypi_0    pypi
jupyter-client            5.3.1                    pypi_0    pypi
jupyter-core              4.5.0                    pypi_0    pypi
numpy                     1.17.0                   pypi_0    pypi
pandas                    0.25.0                   pypi_0    pypi
parso      

In [15]:
import numpy as np

alist = [1,2,3,4,5,'문자'] #여러 타입의 값을 가질 수 있다. 벡터 연산 불가능
arr = np.array([1,2,3,4,5]) #한 가지 타입만 가능. 타입이 다르면 형변환 된다.
arr2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
arr3 = np.array([[[1,2,3,4,5],[10,20,30,40,50]],[[1,2,3,4,5],[10,20,30,40,50]]])

In [18]:
len(alist)

arr + 5 #벡터 연산 가능

array([ 6,  7,  8,  9, 10])

In [22]:
type(arr)
arr[0].dtype #array가 가지는 원소 값의 타입.

dtype('int32')

In [31]:
arr = np.array([10,20,30,40,50],dtype=np.int64)
arr.ndim #차원의 수
arr.shape
arr.dtype
arr[0]=2147483648
arr

array([2147483648,         20,         30,         40,         50],
      dtype=int64)

In [39]:
arr = np.array([1.2,3.4,5.6])
arr2 = arr.astype(np.int32) #타입변경
type(arr)
arr.dtype
arr2.dtype

dtype('int32')

In [41]:
import timeit
#파이썬 list이용
timeit.timeit('[i**2 for i in arr]', setup = 'arr=range(100)')


35.11358456884561

In [45]:
#numpy이용
timeit.timeit('arr**2', 
              setup = 'import numpy as np; arr = np.arange(100)')

0.6684176784098952

In [60]:
#3행 4열

arr = np.array([
                [[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11]],
                [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]   
              ],dtype = np.int32)

print("맨앞차원:",len(arr))
print("차원:",arr.ndim)
print("배열의 모양:",arr.shape)
print("배열의 타입:",type(arr))
print("data의 타입:",arr.dtype)
print("행의 개수 = ", arr.shape[1])
print("열의 개수 = ", arr.shape[2])

for a in arr:
    #print(a)
    for b in a:
        print(b)
        for c in b:
            print(c)

맨앞차원: 2
차원: 3
배열의 모양: (2, 3, 4)
배열의 타입: <class 'numpy.ndarray'>
data의 타입: int32
행의 개수 =  3
열의 개수 =  4
[1 2 3 4]
1
2
3
4
[4 5 6 7]
4
5
6
7
[ 8  9 10 11]
8
9
10
11
[12 13 14 15]
12
13
14
15
[16 17 18 19]
16
17
18
19
[20 21 22 23]
20
21
22
23


In [71]:
#초기값 0 
arr = np.array([1,2,3,4,5])
arr = np.zeros(5, dtype = np.int32)
arr = np.zeros((2,3))
arr = np.zeros((2,3,4))
arr = np.zeros((3,4), dtype = 'U4') #값 길이 제한
arr[0] = '파이썬' #0행 모든 칼럼
arr[0][0] = '파이썬입니다' #0행 0열, 4자리만 가능
arr

array([['파이썬입', '파이썬', '파이썬', '파이썬'],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U4')

In [78]:
#초기값 1 
arr = np.ones(5, dtype = np.int32)
arr = np.ones((2,3))
arr = np.ones((2,3,4))
arr = np.ones((3,4), dtype = 'U4') #값 길이 제한
arr[0] = '파이썬' #0행 모든 칼럼
arr[0][0] = '파이썬입니다' #0행 0열, 4자리만 가능
arr

array([['파이썬입', '파이썬', '파이썬', '파이썬'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U4')

In [83]:
arr = np.empty((5,5))
arr


array([[1.17520042e+180, 3.17095857e+180, 1.23755530e+214,
        5.75677079e+252, 1.28036948e-152],
       [7.75111091e+228, 6.01334637e-154, 1.08365609e+155,
        1.27967305e-152, 6.01347145e-154],
       [9.40785103e+218, 1.69592865e-152, 3.68065907e+180,
        3.58936365e+246, 2.46088966e-154],
       [8.78869628e-106, 1.67793286e+243, 6.10706528e-154,
        4.02241783e+087, 7.20881115e+159],
       [1.78879622e+161, 6.97379781e+228, 1.27967305e-152,
        8.83453771e+199, 6.01347002e-154]])

In [86]:
np.full(shape = 10, fill_value = 3.14)
np.full(shape = (2,5), fill_value = 3)


array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [87]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.linspace(1, 10, 3, dtype = np.int32)

array([ 1,  5, 10])

In [103]:
arr = np.arange(1,10)
print(arr.ndim)
print(arr.shape)

arr.shape = 5,1
print(arr.ndim)
print(arr.shape)
arr

1
(9,)


ValueError: cannot reshape array of size 9 into shape (5,1)

In [118]:
a = np.arange(16)
b = a.reshape(4,4)
b.base is a

#한 쪽의 값이 변경되면 다른 쪽의 값도 변경된다.
b[0] = 99
b[1][1] = 88


In [129]:
a = np.arange(16)
b = a.reshape(4,-1)
e = b.ravel() #모든 원소를 1차원 배열로 리턴
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [144]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.ones((2,5),dtype = np.int32)
arr3 = np.zeros((2,5),dtype = np.int32)
arr4 = np.full((2,5),fill_value = 10)

np.vstack((arr1, arr1, arr2, arr3, arr4)) #아래에 붙음
np.hstack((arr1, arr2)) #옆에 붙음
np.r_[arr1, arr2] # (=np.vstack)
np.c_[arr1, arr2] # (=np.hstack)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])

In [169]:
arr1 = np.zeros((3,3))
arr2 = np.ones((3, 2))
arr3 = np.arange(10,160,10).reshape(3,5)

res1 = np.hstack([arr1, arr2])
res2 = np.vstack([res1, arr3])
np.vstack([res2, res2])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [175]:
arr1 = np.zeros((3,3),dtype = np.int32)
arr2 = np.ones((3,3),dtype = np.int32)

arr1 + arr2
arr1 * arr2
arr1 - arr2
arr1 / arr2


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [182]:
#브로드캐스팅 / 맨 마지막 차원의 수가 같아야 가능.
a = np.array([[10,20,30,40],[50,60,70,80],[90,10,20,30]])
b = np.array([1,2,3,4])
c = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],
              [[10,20,30,40],[50,60,70,80],[90,10,20,30]]])

a + b #a+c와 같은 효과

print(a.shape)
print(b.shape)
print(c.shape)
a + c
b + c


(3, 4)
(4,)
(2, 3, 4)


array([[[ 2,  4,  6,  8],
        [ 2,  4,  6,  8],
        [ 2,  4,  6,  8]],

       [[11, 22, 33, 44],
        [51, 62, 73, 84],
        [91, 12, 23, 34]]])

In [192]:
#크기가 같은 배열끼리는 연산 가능.
#크기가 다른 배열끼리는 브로드 캐스팅
arr1 = np.arange(24).reshape(2,3,4)
arr2 = np.array([2,4,6,8])

arr1 + arr2


array([[[ 2,  5,  8, 11],
        [ 6,  9, 12, 15],
        [10, 13, 16, 19]],

       [[14, 17, 20, 23],
        [18, 21, 24, 27],
        [22, 25, 28, 31]]])

In [201]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = np.zeros_like(x)
#방법1: 직접 looping
# for i in range(10000):
#     z[i] = x[i] + y[i]
#방법2: 벡터화 연산을 한다. (간단, 빠름)
z = x + y

print(z)

[10002 10004 10006 ... 29996 29998 30000]


In [205]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
a==b #array([False, True, False, True])
a>=b #array([False, True, True, True])
np.all(a==b) #모든 요소가 같은지 비교 False 
np.any(a==b) #요소 중 하나라도 같은 값이 있는지 비교 True


True

In [212]:
#range(5): 0<= <5 3개 추출
np.random.choice(5,3,replace=False) #비복원추출
np.random.choice(5,3,replace=True) #복원추출

np.random.choice([10,20,30,40,50],3,replace=True) #복원추출

np.random.choice(5,10) #반복해서 10개 생성

# 선택 확률을 다르게 해서 10개 선택 (0,2,3만 나올 확률 지정)
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) 



array([3, 3, 0, 3, 0, 3, 2, 3, 3, 2])

In [217]:
np.random.rand(3, 5) #0~1사이의 값 들 중 난수생성

np.random.randn(3,5)

np.random.randint(10, 20, size=None)


15

In [221]:
arr = np.array([1,2,10,20,30])
np.where(arr>=10) #index
arr[np.where(arr>=10)] #(array([2, 3, 4], dtype=int64),)
np.where(arr>=10 ,"10이상", "10이하")

#arr[[2,3,4]]

array(['10이하', '10이하', '10이상', '10이상', '10이상'], dtype='<U4')

In [244]:
a = np.arange(16).reshape(2,-1)
np.split(a, [1], axis = 0)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]

In [251]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,1,2,3],
                [10,20,30,40],
                [50,60,70,80],
                [90,10,20,30]
               ])

x, y = np.split(arr, [3], axis=0) #행기준
x, y = np.vsplit(arr, [3])
print(x,y)
x, y = np.split(arr, [2], axis=1) #열기준
x, y = np.hsplit(arr, [2])
print(x,y)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]] [[10 20 30 40]
 [50 60 70 80]
 [90 10 20 30]]
[[ 1  2]
 [ 5  6]
 [ 9  1]
 [10 20]
 [50 60]
 [90 10]] [[ 3  4]
 [ 7  8]
 [ 2  3]
 [30 40]
 [70 80]
 [20 30]]


In [256]:
np.add.reduce([1,2,3,4,5])
np.add.accumulate([1,2,3,4,5])


array([ 1,  3,  6, 10, 15], dtype=int32)

In [257]:
np.sum([1,2,3,4,5])

15