In [ ]:
#numpt 모듈 import

In [ ]:
#data [1,2,3]으로 (3,) 1차원 배열만들기 
#data [1,2,3,4] [5,6,7,8] 으로 (2,4) 2차원 배열만들기 
#data [1,2,3] [4,5,6] [7,8,9] [10,11,12] 으로 (2,2,3) 3차원 배열만들기 

In [16]:
import numpy as np 

arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3,4],[45,6,7,8]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
#1차원 배열,2차원 배열,3차원 배열 각각의 변수들에 대한 차원을 확인한다.

In [21]:
print('arr1=',arr1.ndim,'차원')
print('arr2=',arr2.ndim,'차원')
print('arr3=',arr3.ndim,'차원')

arr1= 1 차원
arr2= 2 차원
arr3= 3 차원


In [ ]:
#각각의 변수들에 대한 형태를 확인한다. (3,) , (2,4), (2,2,3)

In [24]:
print('arr1=', arr1.shape, '형태')
print('arr2=', arr2.shape, '형태')
print('arr3=', arr3.shape, '형태')

arr1= (3,) 형태
arr2= (2, 4) 형태
arr3= (2, 2, 3) 형태


In [ ]:
#ndarray의 데이터타입을 확인한다. 

In [35]:
arr1.dtype
print('arr1의 타입은 {}이고 데이터 타입은 {}이다'.format(type(arr1), arr1.dtype))
print('arr2의 타입은 {}이고 데이터 타입은 {}이다'.format(type(arr2), arr2.dtype))
print('arr3의 타입은 {}이고 데이터 타입은 {}이다'.format(type(arr3), arr3.dtype))


arr1의 타입은 <class 'numpy.ndarray'>이고 데이터 타입은 int32이다
arr2의 타입은 <class 'numpy.ndarray'>이고 데이터 타입은 int32이다
arr3의 타입은 <class 'numpy.ndarray'>이고 데이터 타입은 int32이다


In [ ]:
#list에 저장된 데이터를 이용하여 numpy 배열를 만들고 type과 dtype를 확인한다. 

In [42]:
alist = [1,2,3,4,5]
arr1 = np.array(alist)
print(type(alist))
print(type(arr1))
print('*'*20)

arr2 = np.array(alist, dtype = 'U1')
print(type(alist))
print(type(arr2))
print(arr2.dtype)
print('*'*20)

arr3 = np.array(alist, dtype = np.float64)
print(type(alist))
print(type(arr3))
print(arr3.dtype)
print('*'*20)


<class 'list'>
<class 'numpy.ndarray'>
********************
<class 'list'>
<class 'numpy.ndarray'>
<U1
********************
<class 'list'>
<class 'numpy.ndarray'>
float64
********************


In [ ]:
#int를 float64 타입으로  float를 int64타입으로 변경한다. 

In [52]:
arr1 = np.array([1,2,3])
f_arr1 = np.array(arr1, dtype = np.float64)
#arr1.np.astype(np.float64)

arr2 = np.array([3.14,2.414,6.789])
i_arr2 = np.array(arr2, dtype = np.int64)

print(arr1, '==>', n_arr1)
print(arr2, '==>', i_arr2)

[1 2 3] ==> [1. 2. 3.]
[3.14  2.414 6.789] ==> [3 2 6]


In [ ]:
#ndarray를 편리하게 생성한다. 
#arange, zeros, ones

In [60]:
arr1 = np.arange(10)
arr2 = np.zeros(10, dtype = np.int32)
arr3 = np.ones(10, dtype = np.int32)

print("연속적인 숫자로 1차원 배열만들기:", arr1.shape, arr1)
print("연속적인 숫자로 1차원 배열만들기:", arr2.shape, arr2)
print("연속적인 숫자로 1차원 배열만들기:", arr3.shape, arr3)

arr4 = arr2.reshape(5, -1)
arr5 = arr3.reshape(5, -1)
print("연속적인 숫자로 2차원(5,2) 배열만들기:", arr4.shape, '\n', arr4)
print("연속적인 숫자로 2차원(5,2) 배열만들기:", arr5.shape, '\n', arr5)


연속적인 숫자로 1차원 배열만들기: (10,) [0 1 2 3 4 5 6 7 8 9]
연속적인 숫자로 1차원 배열만들기: (10,) [0 0 0 0 0 0 0 0 0 0]
연속적인 숫자로 1차원 배열만들기: (10,) [1 1 1 1 1 1 1 1 1 1]
연속적인 숫자로 2차원(5,2) 배열만들기: (5, 2) 
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
연속적인 숫자로 2차원(5,2) 배열만들기: (5, 2) 
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
#ndarray의 차원의 크기를 변경하기 : reshape, -1이용 

In [76]:
arr1 = np.arange(10)
arr2 = arr1.reshape(5, -1).copy()
print('arr1:', arr1)
print('arr2:', arr2.shape, '\n', arr2)

arr1: [0 1 2 3 4 5 6 7 8 9]
arr2: (5, 2) 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#1차원을 2차원, 3차원으로 변경하기 

In [67]:
arr2 = np.arange(18).reshape(2, 9)
arr3 = np.arange(18).reshape(3, 2, 3)
print('arr2:', arr2.shape, '\n', arr2)
print('arr3:', arr3.shape, '\n', arr3)

arr2: (2, 9) 
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
arr3: (3, 2, 3) 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [ ]:
#3차원을 2차원으로 변경하기 

In [70]:
arr3.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [ ]:
#numpy array를 list로 변환하기 

In [102]:
arr = np.arange(18).reshape(3,2,3)
print(arr, type(arr))
alist = arr.tolist() #array -> list
print(alist, type(alist))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]] <class 'numpy.ndarray'>
[[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]], [[12, 13, 14], [15, 16, 17]]] <class 'list'>


In [ ]:
#numpy의 ndarray의 데이터 세트 선택하기
1. 특정 데이터만 추출 ~ 위치이용 
2. 슬라이싱 ~ 연속 인덱싱 이용 
3. 팬시 인덱싱 ~ 일정한 인덱싱 집합을 리스트 또는 ndarray형태로 지정해 해당 위치에 있는 ndarray를 반환
4. 불린 인덱싱 ~ 특정 조건에 해당하는지 여부 true/false값 인덱싱 집합을 기반으로 
                 true에 해당하는 인덱싱 위치에 있는 데이터의 ndarray반환 

In [ ]:
#1부터 9까지 1차원 배열을 생성
#3번째 데이터값을 추출한다.
#맨뒤의 값을 추출 
#맨뒤의 값을 100으로 수정하고 확인  

In [108]:
arr = np.arange(1, 10)
print("3번째 데이터값을 추출: {}\n 맨뒤 데이터값을 추출: {}".format(arr[3], arr[-1]))
arr[-1] = 100
print("맨뒤 데이터값을 추출: {}".format(arr[-1]))

3번째 데이터값을 추출: 4
맨뒤 데이터값을 추출: 9
맨뒤 데이터값을 추출: 100


In [ ]:
#2차원으로 변경하기
#맨뒤 데이터값을 추출

In [130]:
arr2 = arr.reshape(3, -1).copy()
print("2차원 데이터:\n", arr2)
print("맨뒤 데이터값을 추출(-이용): ", arr2[-1][-1])
print("맨뒤 데이터값을 추출(위치이용):", arr2[2][2])


2차원 데이터:
 [[  1   2   3]
 [  4   5   6]
 [  7   8 100]]
맨뒤 데이터값을 추출(-이용):  100
맨뒤 데이터값을 추출(위치이용): 100


In [ ]:
#슬라이싱
#데이터 0~2번째
#데이터 0~2번째..처음생략가능
#데이터 3번째부터 끝까지 
#슬라이싱을 이용한 모두추출

In [137]:
arr = np.arange(1,10)
print("데이터:", arr)
print("데이터 0~2번째:",arr[0:3])
print("데이터 0~2번째, 처음생략가능:",arr[:3])
print("데이터 3번째부터 끝까지:",arr[3:])
print("슬라이싱을 이용한 모두 추출:",arr[:])

데이터: [1 2 3 4 5 6 7 8 9]
데이터 0~2번째: [1 2 3]
데이터 0~2번째, 처음생략가능: [1 2 3]
데이터 3번째부터 끝까지: [4 5 6 7 8 9]
슬라이싱을 이용한 모두 추출: [1 2 3 4 5 6 7 8 9]


In [ ]:
#2차원 슬라이싱
#데이터 0행 0~2번째
#데이터 0행 0~2번째..처음생략가능
#데이터 0행 3번째부터 끝까지 
#데이터 모든행 0~2번째
#데이터 모든행 0~2번째..처음생략가능
#데이터 모든행 3번째부터 끝까지 
#슬라이싱을 이용한 모두추출

In [184]:
arr = np.arange(1,11).reshape((2,5))
print("데이터:\n", arr)
print("데이터 0행 0~2번째:\n", arr[0][0:3])
print("데이터 0행 0~2번째..처음생략가능:\n", arr[0][:3])
print("데이터 0행, 3번째부터 끝까지:\n", arr[:, 0:3])
print("데이터 모든행 0~2번째:\n", arr[:, 0:3])
print("데이터 모든행 0~2번째..처음생략가능:\n", arr[:, :3])
print("데이터 모든행, 3번째부터 끝까지:\n", arr[:, 3:])
print("슬라이싱을 이용한 모두 추출:\n", arr[:])

데이터:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
데이터 0행 0~2번째:
 [1 2 3]
데이터 0행 0~2번째..처음생략가능:
 [1 2 3]
데이터 0행, 3번째부터 끝까지:
 [[1 2 3]
 [6 7 8]]
데이터 모든행 0~2번째:
 [[1 2 3]
 [6 7 8]]
데이터 모든행 0~2번째..처음생략가능:
 [[1 2 3]
 [6 7 8]]
데이터 모든행, 3번째부터 끝까지:
 [[ 4  5]
 [ 9 10]]
슬라이싱을 이용한 모두 추출:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#팬시 인덱싱 
#0행과 1행 모든 열
#0행과 1행의 2열 
#0행과 1행의 0~2열

In [186]:
arr = np.arange(1,11).reshape((2,5))
print("0행과 1행 모든 열:", arr[:])
print("0행과 1행의 2열:", arr[:, 2])
print("0행과 1행의 0~2열:", arr[:,:3])

0행과 1행 모든 열: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
0행과 1행의 2열: [3 8]
0행과 1행의 0~2열: [[1 2 3]
 [6 7 8]]


In [ ]:
#불린인덱싱 ~ 조건 필터링과 검색이 동시가능 
# 짝수번째 인덱싱 결과를 출력 
# 짝수번째 인덱싱 필터 결과 출력 

In [214]:
arr = np.arange(1,11)

print("boolean값: ", arr%2 == 0)
print("짝수번째 값: ", arr[arr%2 == 0])

boolean값:  [False  True False  True False  True False  True False  True]
짝수번째 값:  [ 2  4  6  8 10]


In [ ]:
#행렬의 정렬 - np.sort(객체), 객체.sort()  argsort()

In [198]:
arr = np.array([3, 10, 2, 9, 5])
print("original data:", arr)
print("sort후 data: ", np.sort(arr))
print("original data:", arr)
print("-"*30)
print("original data:", arr)
print("sort후 data: ", arr.sort())
print("original data:", arr)

original data: [ 3 10  2  9  5]
sort후 data:  [ 2  3  5  9 10]
original data: [ 3 10  2  9  5]
------------------------------
original data: [ 3 10  2  9  5]
sort후 data:  None
original data: [ 2  3  5  9 10]


In [ ]:
#행기준1.. axis생략.. sort
#행기준1.. axis이용.. sort
#열기준 sort

In [201]:
arr = np.array([[8,12],[7,1]])
print("original data:\n", arr)
print("행기준1..axis생략..sort후:\n",
     np.sort(arr))
print("행기준1..axis이용..sort후:\n",
     np.sort(arr, axis = 0))
print("열기준 sort후:\n",
     np.sort(arr, axis = 1))


original data:
 [[ 8 12]
 [ 7  1]]
행기준1..axis생략..sort후:
 [[ 8 12]
 [ 1  7]]
행기준1..axis이용..sort후:
 [[ 7  1]
 [ 8 12]]
열기준 sort후:
 [[ 8 12]
 [ 1  7]]


In [ ]:
#정렬된 행렬의 인덱스 추출
#반환된 인덱스를 이용해 원본 데이터 추출 
#인덱스 배열을 이용한 원본데이터 추출

In [203]:
arr = np.array([3, 10, 2, 9, 5])
print("original data:", arr)
sort_index =  np.argsort(arr)
print("sort index추출: ", sort_index)
print("인덱스 배열을 이용한 원본데이터 추출: ", arr[sort_index])

original data: [ 3 10  2  9  5]
sort index추출:  [2 0 4 3 1]
인덱스 배열을 이용한 원본데이터 추출:  [ 2  3  5  9 10]


In [ ]:
#선행대수 연산 - 행렬곱과 전치행렬 구하기 

In [219]:
arr1 = np.array([[1,2,3],[4,5,6]]) #2, 3
arr2 = np.array([[7,8],[9,10],[11,12]]) #3, 2
np.dot(arr1,arr2)
np.matmul(arr1,arr2)
arr1@arr2

print("(2,3)행렬 * (3,2)행렬 = (2,2)")
print("행렬곱=\n", np.dot(arr1,arr2))

(2,3)행렬 * (3,2)행렬 = (2,2)
행렬곱=
 [[ 58  64]
 [139 154]]


In [ ]:
#전치행렬
arr1 = np.array([[1,2,3],[4,5,6]])

In [213]:
arr1 = np.array([[1,2,3],[4,5,6]])
print("original data:\n", arr1)
print("전치행렬 data:\n", np.transpose(arr1))
print("전치행렬 data:\n", arr1.T)

original data:
 [[1 2 3]
 [4 5 6]]
전치행렬 data:
 [[1 4]
 [2 5]
 [3 6]]
전치행렬 data:
 [[1 4]
 [2 5]
 [3 6]]
